global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: kafka-rest-proxy-go
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka-rest-proxy-go:8080
